config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :reality_checks
  end
  get 'home/landing_page'
  # get 'flic', to: 'reality_checks#create'

  get 'log_in' => 'sessions#new', as: 'login'
  post 'log_in' => 'sessions#create'
  get 'log_out' => 'sessions#destroy', as: 'logout'
  get 'users/:id/dashboard' => 'users#dashboard', as: 'dashboard'

  root 'users#show'
end

app/models/reality_check.rb
class RealityCheck < ApplicationRecord
	belongs_to :user
	  scope :today, -> { where "created_at >= ? ", DateTime.current.beginning_of_day + 4.hours }

end

app/controllers/reality_checks_controller.rb
class RealityChecksController < ApplicationController
  # this set reality check method gets called before teh actions specified in the array 
  before_action :set_reality_check, only: [:show, :edit, :update, :destroy]

  def index
    @reality_checks =
    if user.admin
      RealityCheck.all
    else
      RealityCheck.where(user_id: current_user.id)
    end
  end


  def show
    # set reality check does the first line and rails implicity does the second
    
    # @user = User.find_by(user_params)
    # render 'show'
  end

  # GET /reality_checks/new
  def new
    @reality_check = RealityCheck.new
  end

  # GET /reality_checks/1/edit
  def edit
    redirect_back unless admin, notice: 'You Cant Change The Past!!'
  end

  # POST /reality_checks
  # POST /reality_checks.json
  def create
    @reality_check = RealityCheck.new(reality_check_params)

    respond_to do |format|
      if @reality_check.save
        format.html { redirect_to @reality_check, notice: 'Reality check was successfully created.' }
        format.json { render :show, status: :created, location: @reality_check }
      else
        format.html { render :new }
        format.json { render json: @reality_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reality_checks/1
  # PATCH/PUT /reality_checks/1.json
  def update
    respond_to do |format|
      if @reality_check.update(reality_check_params)
        format.html { redirect_to @reality_check, notice: 'Reality check was successfully updated.' }
        format.json { render :show, status: :ok, location: @reality_check }
      else
        format.html { render :edit }
        format.json { render json: @reality_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reality_checks/1
  # DELETE /reality_checks/1.json
  def destroy
    if admin
    @reality_check.destroy
    respond_to do |format|
      format.html { redirect_to reality_checks_url, notice: 'Reality check was successfully destroyed.' }
      format.json { head :no_content }
    end
    else
      redirect_to dashboard, notice: "You Can't Undo The Past!!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reality_check
      @reality_check = RealityCheck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reality_check_params
      params.fetch(:reality_check, {:user_id})
    end
end

app/helpers/reality_checks_helper.rb
module RealityChecksHelper
  def yesterdays_checks_count
    # @user.authenticate
    @yesterday_checks = RealityCheck.where(created_at: @yesterday..@start_of_day, user_id: @user.id)
    @yesterday_checks ? @yesterday_checks.count : 0
  end
end

app/views/reality_checks/_form.html.erb
<%= form_with(model: reality_check, local: true) do |form| %>
  <% if reality_check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reality_check.errors.count, "error") %> prohibited this reality_check from being saved:</h2>

      <ul>
      <% reality_check.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reality_checks/edit.html.erb
<h1>Editing Reality Check</h1>

<%= render 'form', reality_check: @reality_check %>

<%= link_to 'Show', @reality_check %> |
<%= link_to 'Back', reality_checks_path %>

app/views/reality_checks/index.html.erb
<p id="notice"><%= notice %></p>
<!--
  <h1>Reality Checks</h1>

@today:<%=@today.strftime("%a %I:%M%P %Z") %>
<br>
<br>
time.now:<%= Time.now.strftime("%a %I:%M%P %Z") %><br>
time.zone.now:<%= Time.zone.now.strftime("%a %I:%M%P %Z") %><br>
time.zone<%= Time.zone %><br>
DateTime.current<%= DateTime.current.strftime("%a %I:%M%P %Z") %><br>
@timezone<%= @timezone %><br>
Date time now in time zone <%= @today.strftime ("%a %I:%M%P %Z") %><br>


<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if user.admin? %>
    <% @reality_checks.each do |reality_check| %>
      <tr>
        <td><%= reality_check.id%> <%=reality_check.created_at.strftime("%a %I:%M%P")%></td>
        <td><%= link_to 'Show', reality_check %></td>
        <td><%= link_to 'Edit', edit_reality_check_path(reality_check) %></td>
        <td><%= link_to 'Destroy', reality_check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
<p>Today you reality checked <%= @reality_checks_today.count %> times!</p>



  <tbody>

    <td> <hr> Today<hr></td>
    <% @reality_checks_today.each do |reality_check| %>
      <tr>

        <td><%= reality_check.id%> <%=reality_check.created_at.in_time_zone(@timezone).strftime("%a %I:%M%P")%></td>

      </tr>
    <% end %>
  </tbody>

  <tbody>

    <td> <hr> yesterday<hr></td>
    <% yesterdays_checks.each do |reality_check| %>
      <tr>
  <% @number += 1 %>
        <td><%= reality_check.id%> <%=reality_check.created_at.in_time_zone(@timezone).strftime("%a %I:%M%P")%></td>

      </tr>
    <% end %>
  </tbody>

</table>
<br>
!-->
<%= link_to 'New Reality Check', new_reality_check_path %>

app/views/reality_checks/new.html.erb
<h1>New Reality Check</h1>

<%= render 'form', reality_check: @reality_check %>

<%= link_to 'Back', reality_checks_path %>

app/views/reality_checks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reality_check_path(@reality_check) %> |
<%= link_to 'Back', reality_checks_path %>