config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :reality_checks
  end
  get 'home/landing_page'
  # get 'flic', to: 'reality_checks#create'

  get 'log_in' => 'sessions#new', as: 'login'
  post 'log_in' => 'sessions#create'
  get 'log_out' => 'sessions#destroy', as: 'logout'
  get 'users/:id/dashboard' => 'users#dashboard', as: 'dashboard'

  root 'users#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>heylucid</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <style>
  body,h1,h2{font-family: "Raleway", sans-serif}
  body, html {height: 100%}
  p {line-height: 2}
  .bgimg{
      min-height: 100%;
      background-position: center;
      background-size: cover;
  }
  .bgimg {background-image: url("https://www.publicdomainpictures.net/pictures/240000/velka/pink-blue-background.jpg")}
  </style>
  <body>
    <nav class='navbar'>
        <% if logged_in? %>
           <%= current_user.email %>
           <%= link_to("Log Out", logout_path) %>
        <% else %>
          <%= link_to 'Log In', login_path, class:'nav-btn' %>
          <%= link_to 'Register', new_user_path, class:'nav-btn' %>
        <% end %>
    </nav>
    <% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>
    <%= yield %>
  </body>
</html>